Modularize CAP pipeline
SUSE/cap pull request #27
Opened 2020-06-02 15:25 UTC by HartS

Changes in this PR:
- Break down jobs into component files
- Collapse repitition in many places
- Rename option to avail (HA vs SA)
- Integrate several newer merges to master

2020-06-02 17:26 UTC, prabalsharma commented on cap-ci/cap-pre-release.yaml.tmpl
> +  cf-acceptance-tests-brain: false
should be true by default same for other jobs.

2020-06-02 21:38 UTC, prabalsharma commented on cap-ci/scripts/destroy_k8s.tmpl
> +# delete k8s cluster
I guess you are using `{{- /*  */ }}` for comments

2020-06-03 21:27 UTC, bikramnehra requested changes
Its really hard to go through all the files to check for consistency, however overall the structure looks good. Hopefully one full test case has been run using this pipeline structure.

2020-06-03 21:27 UTC, bikramnehra commented on cap-ci/cap-pre-release.yaml.tmpl
>  # Currently only accepts disabling jobs if all later jobs are also disabled.
Is this still true? I thought this PR will address dependency issues.

2020-06-03 21:27 UTC, bikramnehra commented on cap-ci/cap-pre-release.yaml.tmpl
> +s3:
This should be `CAP` bundle and not `kubecf`. 

```
bucket: cap-release-artifacts
regexp: CAP-(.*).tgz
```

2020-06-03 21:30 UTC, HartS commented on cap-ci/cap-pre-release.yaml.tmpl
>  # Currently only accepts disabling jobs if all later jobs are also disabled.
Good catch, thanks!

2020-06-03 21:32 UTC, HartS commented on cap-ci/cap-pre-release.yaml.tmpl
> +s3:
@bikramnehra  this is consistent with master right now
- https://github.com/SUSE/cap/blob/a55a04a1133a99a5de0c3dac9b13e52ed60fc584/cap-ci/cap-pre-release.yaml#L2
- https://github.com/SUSE/cap/blob/a55a04a1133a99a5de0c3dac9b13e52ed60fc584/cap-ci/pipeline.template#L63

cap-release does indeed use the `CAP-(.*).tgz` regexp

2020-06-03 22:02 UTC, bikramnehra approved these changes
LGTM.

2020-06-03 22:16 UTC, merged