Extended pipeline creator and template with parametrization of brain tests.
SUSE/cap pull request #4
Opened 2020-04-07 19:54 UTC by andreas-kupries

Ref: https://jira.suse.com/browse/CAP-1353

See also https://github.com/SUSE/catapult/pull/160 and https://github.com/SUSE/brain-tests-release/pull/12

Testing: Created and then inspected a pipeline definition. Not uploaded to a concourse though. Requires the above-referenced catapult and brain-test-release work to be properly functional.

2020-04-08 08:42 UTC, viccuad requested changes
Given that Catapult has its defaults that the pipeline is already using, do we expect to change `BRAIN_* ` options so regularly that we need to have them parametrized on the pipeline?

If the idea is to tune them for developing and iterating on the pipeline, I would suggest to just add them manually on params in the pipeline.template. Once done, discard the deployed copy of the pipeline and the changes.

2020-04-08 16:27 UTC, andreas-kupries commented
While providing env variables to the `create_cap-release_pipeline.sh` script is certainly as manual as editing the pipeline template, or generated pipeline, IMHO the latter is a much more error-prone process than, for example, pulling the create invokation out of the terminal history, putting a few more assignments in front of the command and then re-running it.

It seems that your request for change is to drop the PR entirely ?

@prabalsharma Do you wish to comment here ? As the original requester of the feature ?

2020-04-08 17:00 UTC, prabalsharma commented
I agree with @andreas-kupries, doing it in this way is less error prone. Also, makes it easier for engineers to know about this feature.
It is important to have this level of parametrisation in CI, especially for brains. This brain parametrisation was so important that we had to add this feature in our old CI during a release cycle. Thus, trying to handle this in advance, this time around.

2020-04-08 21:11 UTC, andreas-kupries commented
Tested this on `concourse.suse.dev` using a disposable `diego-caasp4-sa` pipeline with the brain tests as first testsuite. Deployment was ok and showed that the configured brain settings were properly injected into the deployment container environment.

As this did use catapult `master`, and kubecf `v1.0.1` the settings were then of course ignored, and the brain tests themselves had a number of expected failures.

None of which speaks against this PR itself.

It should be possible to test further propagation into the system when https://github.com/SUSE/catapult/pull/160 is merged and available.

2020-04-09 07:48 UTC, viccuad approved these changes
Approving then. Yet, I still see not much value in it; if BRAINS pass with the default config, I see no need to change the config so often when deploying a pipeline.

And for making people discover all knobs, we are better served just pointing them at `catapult/buildfolder/defaults.sh`.

2020-04-09 16:18 UTC, merged