Update s3.kubecf regexp to new artifact format
SUSE/cap pull request #72
Opened 2020-11-10 10:48 UTC by viccuad

`kubecf-bundle-v(.*)-(.*\..*).tgz`:
- 1st capturing group is the semver, as expected in
  https://github.com/concourse/s3-resource#file-names
  "The first grouped match is used to extract the version".
- 2nd capturing group is our artifact information: expect anything, but at least
  1 dot in the middle of the group. The idea here is a bit of future-proofing,
  if we drop the number of commits in the middle.

2020-11-16 18:47 UTC, prabalsharma commented
This new regex should not be part of cap-pre-release yamls as cap-release CI is to test kubecf RC, for which `regexp: kubecf-bundle-v(.*).tgz` should suffice. This PR is more inclined towards cap-nightly CI card https://jira.suse.com/browse/CAP-1638 and this new regex should be part of cap-nighlty yamls. Unless we decide to not test kubecf RC, in that case we can use cap-pre-release to test kubecf master builds.

2020-11-16 18:48 UTC, prabalsharma requested changes
This new regex should not be part of cap-pre-release yamls as cap-pre-release CI is to test kubecf RC, for which regexp: kubecf-bundle-v(.*).tgz should suffice. This PR is more inclined towards cap-nightly CI card https://jira.suse.com/browse/CAP-1638 and this new regex should be part of cap-nighlty yamls. Unless we decide to not test kubecf RC, in that case we can use cap-pre-release yamls to test kubecf master builds.

2020-11-17 13:15 UTC, viccuad commented
I see. But there is no concept of KubeCF RCs. If we want that, we should open an issue or an RFD, and lobby for it.
KubeCF releases normally get cut directly from master, when master pipeline is completely green. Yet, KubeCF releases may have cherry-picked changes after they are cut.

Artifacts from KubeCF master get built at the end of the pipeline. The idea is to only have a bundle from master if the pipeline has passed. This is incomplete right now, as the bundle gets created if all the Diego lane is green, but doesn't wait until the Eirini or Upgrade lanes are green too (this would be something to fix, if we care about KubeCF master artifacts).

The cap-pre-release pipeline could either use KubeCF master builds, or KubeCF releases for now.
If we want KubeCF master builds, we can follow the approach in this PR.
If we want KubeCF releases, then we just need to consume whatever latest release is. Which is the same as the current behaviour outside of this PR, with `regexp: kubecf-bundle-v(.*).tgz`.

2020-11-17 18:06 UTC, prabalsharma commented
Yes, I agree with you on the info you provided here. 

By kubecf RC I meant kubecf releases (my bad) : 

```
2020-03-11 03:05:41      56068 kubecf-v1.0.0.tgz
2020-06-03 07:23:39      81930 kubecf-v2.2.2.tgz
2020-08-13 16:32:37      83196 kubecf-v2.2.3.tgz
2020-07-13 10:54:02      83978 kubecf-v2.3.0.tgz
2020-09-23 03:04:19      89733 kubecf-v2.5.0.tgz
2020-10-02 02:30:04      99157 kubecf-v2.5.3.tgz
2020-10-02 16:03:13      99167 kubecf-v2.5.4.tgz
2020-10-06 05:08:49      99160 kubecf-v2.5.5.tgz
2020-10-07 04:06:14      99290 kubecf-v2.5.6.tgz
2020-10-08 04:55:09      98869 kubecf-v2.5.7.tgz
2020-10-09 18:27:49      99194 kubecf-v2.5.8.tgz
2020-10-27 03:56:56     100190 kubecf-v2.6.1.tgz
```

Considering cap-pre-release right now has a regex to pick up kubecf releases, I think we can create a new set of yamls to pick up masters as part of https://jira.suse.com/browse/CAP-1638 with your new regex. I have added you regex in a comment there. We can close this PR IMO.

2020-11-18 09:26 UTC, viccuad commented
Closing then.

2020-11-18 09:26 UTC, closed without merging